---
- name: Instal neccecary packages
  apt: name=curl state=present
  register: curl_installed


# Download Nodejs
- name: Download nodejs from node.source
  command: bash -c "curl -sL https://deb.nodesource.com/setup | sudo bash -"
  when: curl_installed|failed

# Update the cache
- name: Update apt cache
  apt:  update_cache=yes
